name: Build FFmpeg AAR and Android App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_ffmpeg_aar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout FFmpeg Kit Repository
        uses: actions/checkout@v3
        with:
          repository: arthenica/ffmpeg-kit
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ffmpeg-kit

      - name: Set up Android SDK and NDK
        run: |
          echo "##[group]Setting up Android SDK and NDK"
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk wget unzip
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip -d $HOME/cmdline-tools
          mkdir -p $HOME/Android/Sdk/cmdline-tools
          mv $HOME/cmdline-tools $HOME/Android/Sdk/cmdline-tools/latest
          yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --update
          $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-30" "ndk;25.1.8937393"
          echo "ANDROID_SDK_ROOT=$HOME/Android/Sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$HOME/Android/Sdk/ndk/25.1.8937393" >> $GITHUB_ENV
          echo "##[endgroup]"

      - name: Build FFmpeg AAR
        run: |
          echo "##[group]Building FFmpeg AAR"
          cd ffmpeg-kit
          ./android.sh
          echo "##[endgroup]"

      - name: Upload FFmpeg AAR as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-kit.aar
          path: ffmpeg-kit/prebuilt/bundle-android-aar/ffmpeg-kit.aar

  build_android_app:
    needs: build_ffmpeg_aar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Android Project
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adoptopenjdk'
          version: '11'

      - name: Download FFmpeg AAR
        uses: actions/download-artifact@v4
        with:
          name: ffmpeg-kit.aar

      - name: Set up Android SDK
        run: |
          echo "##[group]Setting up Android SDK"
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk wget unzip
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip -d $HOME/cmdline-tools
          mkdir -p $HOME/Android/Sdk/cmdline-tools
          mv $HOME/cmdline-tools $HOME/Android/Sdk/cmdline-tools/latest
          yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --update
          $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-30"
          echo "ANDROID_SDK_ROOT=$HOME/Android/Sdk" >> $GITHUB_ENV
          echo "##[endgroup]"

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Build Android App
        run: |
          echo "##[group]Building Android App"
          cp ffmpeg-kit.aar app/libs/
          ./gradlew build
          echo "##[endgroup]"
